# frozen_string_literal: true

source "https://rubygems.org"

# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rspec'
gem 'ffi', '>= 1.9.24' # address ffi vulnerability

group :development do
  gem 'rb-readline'
  gem 'guard'
  gem 'guard-rspec'
end
